// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/java/LexerColor.flex

import compilerTools.TextColor;
import java.awt.Color;


@SuppressWarnings("fallthrough")
class LexerColor {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\12\0\1\1\1\2\1\0\1\3\22\0\1\4\1\5"+
    "\1\6\1\7\3\0\3\10\1\11\1\12\1\10\1\13"+
    "\1\14\1\15\1\16\11\17\2\10\1\20\1\21\1\22"+
    "\2\0\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\2\32\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\32\1\47"+
    "\1\50\1\32\1\10\1\0\1\10\1\0\1\32\1\0"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\32"+
    "\1\60\2\32\1\61\1\62\1\63\1\64\1\65\1\66"+
    "\1\67\1\70\1\71\1\72\1\73\1\32\1\74\1\50"+
    "\1\32\1\10\1\4\1\10\7\0\1\2\73\0\1\75"+
    "\7\0\1\75\3\0\1\75\3\0\1\75\1\0\1\76"+
    "\6\0\1\77\1\0\1\75\1\10\3\0\1\75\7\0"+
    "\1\75\3\0\1\75\3\0\1\75\1\0\1\76\6\0"+
    "\1\75\1\0\1\75\1\10\u012a\0\2\2\326\0\u0100\2";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\3\1\1\2\1\1\4\2\2\3\1\2\12\1"+
    "\1\2\22\1\3\0\1\4\2\5\1\6\7\1\1\7"+
    "\1\1\1\7\26\1\1\7\2\1\1\7\10\1\3\0"+
    "\2\4\11\1\1\10\6\1\1\7\42\1\2\0\1\4"+
    "\47\1\1\0\2\1\1\11\25\1\1\0\12\1\1\12"+
    "\4\1";

  private static int [] zzUnpackAction() {
    int [] result = new int[232];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\100\0\200\0\300\0\u0100\0\u0140\0\100\0\u0180"+
    "\0\u01c0\0\u0200\0\u0240\0\u0280\0\300\0\u02c0\0\u0300\0\u0340"+
    "\0\u0380\0\u03c0\0\u0400\0\u0440\0\u0480\0\u04c0\0\u0500\0\u0300"+
    "\0\u0540\0\u0580\0\u05c0\0\u0600\0\u0640\0\u0680\0\u06c0\0\u0700"+
    "\0\u0740\0\u0780\0\u07c0\0\u0800\0\u0840\0\u0880\0\u08c0\0\u0900"+
    "\0\u0940\0\u0980\0\u0100\0\u09c0\0\u0a00\0\u0a40\0\100\0\u0a80"+
    "\0\100\0\u0ac0\0\u0b00\0\u0b40\0\u0b80\0\u0bc0\0\u0c00\0\u0c40"+
    "\0\u0c80\0\u0cc0\0\u0d00\0\u0d40\0\u0d80\0\u0dc0\0\u0e00\0\u0e40"+
    "\0\u0e80\0\u0ec0\0\u0f00\0\u0f40\0\u0f80\0\u0fc0\0\u1000\0\u1040"+
    "\0\u1080\0\u10c0\0\u1100\0\u1140\0\u1180\0\u11c0\0\u1200\0\u1240"+
    "\0\u1280\0\u12c0\0\u1300\0\u1340\0\u1380\0\u13c0\0\u1400\0\u1440"+
    "\0\u1480\0\u14c0\0\u1500\0\u1540\0\u1580\0\u15c0\0\u1600\0\u1640"+
    "\0\100\0\u1680\0\u16c0\0\u1700\0\u1740\0\u1780\0\u17c0\0\u1800"+
    "\0\u1840\0\u1880\0\u18c0\0\u0300\0\u1900\0\u1940\0\u1980\0\u19c0"+
    "\0\u1a00\0\u1a40\0\u0300\0\u1a80\0\u1ac0\0\u1b00\0\u1b40\0\u1b80"+
    "\0\u1bc0\0\u1c00\0\u1c40\0\u1c80\0\u1cc0\0\u1d00\0\u1d40\0\u1d80"+
    "\0\u1dc0\0\u1e00\0\u1e40\0\u1e80\0\u1ec0\0\u1f00\0\u1f40\0\u1f80"+
    "\0\u1fc0\0\u2000\0\u2040\0\u2080\0\u20c0\0\u2100\0\u2140\0\u2180"+
    "\0\u21c0\0\u2200\0\u2240\0\u2280\0\u22c0\0\u2300\0\u2340\0\u1600"+
    "\0\u2380\0\u23c0\0\u2400\0\u2440\0\u2480\0\u24c0\0\u2500\0\u2540"+
    "\0\u2580\0\u25c0\0\u2600\0\u2640\0\u2680\0\u26c0\0\u2700\0\u2740"+
    "\0\u2780\0\u27c0\0\u2800\0\u2840\0\u2880\0\u28c0\0\u2900\0\u2940"+
    "\0\u2980\0\u29c0\0\u2a00\0\u2a40\0\u2a80\0\u2ac0\0\u2b00\0\u2b40"+
    "\0\u2b80\0\u2bc0\0\u2c00\0\u2c40\0\u2c80\0\u2cc0\0\u2d00\0\u2d40"+
    "\0\u2d80\0\u2dc0\0\u0300\0\u2e00\0\u2e40\0\u2e80\0\u2ec0\0\u2f00"+
    "\0\u2f40\0\u2f80\0\u2fc0\0\u3000\0\u3040\0\u3080\0\u30c0\0\u3100"+
    "\0\u3140\0\u3180\0\u31c0\0\u3200\0\u3240\0\u3280\0\u32c0\0\u3300"+
    "\0\u3340\0\u3380\0\u33c0\0\u3400\0\u3440\0\u3480\0\u34c0\0\u3500"+
    "\0\u3540\0\u3580\0\u35c0\0\100\0\u3600\0\u3640\0\u3680\0\u36c0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[232];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\2\1\0\1\3\1\2\1\4\1\5\1\6\2\7"+
    "\1\10\1\11\1\7\1\12\1\13\1\14\1\15\1\16"+
    "\1\15\1\17\1\20\1\21\1\22\1\23\1\24\2\17"+
    "\1\25\1\17\1\26\1\27\1\30\1\31\1\17\1\32"+
    "\1\33\1\34\1\17\1\35\1\17\1\30\1\17\1\36"+
    "\1\37\1\40\1\41\1\42\1\17\1\43\1\17\1\44"+
    "\1\45\1\30\1\46\1\17\1\47\1\50\1\51\1\17"+
    "\1\52\2\17\1\30\1\17\101\0\1\2\117\0\1\7"+
    "\64\0\1\7\4\0\2\53\1\0\2\53\3\0\52\53"+
    "\7\0\1\54\11\0\2\54\3\0\55\54\12\0\1\7"+
    "\100\0\1\7\75\0\1\55\3\0\1\56\100\0\1\57"+
    "\1\60\76\0\2\14\101\0\1\7\1\61\73\0\2\17"+
    "\3\0\55\17\16\0\2\17\3\0\14\17\1\62\24\17"+
    "\1\63\13\17\16\0\2\17\3\0\11\17\1\64\2\17"+
    "\1\65\21\17\1\66\16\17\16\0\2\17\3\0\4\17"+
    "\1\67\25\17\1\70\22\17\16\0\2\17\3\0\13\17"+
    "\1\71\10\17\1\72\13\17\1\73\10\17\1\74\3\17"+
    "\16\0\2\17\3\0\1\75\7\17\1\76\1\77\14\17"+
    "\1\100\6\17\1\101\1\102\16\17\16\0\2\17\3\0"+
    "\12\17\1\103\1\104\23\17\1\105\1\106\14\17\16\0"+
    "\2\17\3\0\10\17\1\107\44\17\16\0\2\17\3\0"+
    "\14\17\1\30\24\17\1\30\12\17\1\110\16\0\2\17"+
    "\3\0\1\111\25\17\1\112\26\17\16\0\2\17\3\0"+
    "\1\113\3\17\1\114\7\17\1\115\11\17\1\116\3\17"+
    "\1\117\6\17\1\120\13\17\16\0\2\17\3\0\1\121"+
    "\7\17\1\122\5\17\1\123\7\17\1\124\6\17\1\125"+
    "\5\17\1\126\11\17\16\0\2\17\3\0\4\17\1\127"+
    "\7\17\1\130\15\17\1\131\6\17\1\132\13\17\16\0"+
    "\2\17\3\0\4\17\1\133\25\17\1\134\22\17\16\0"+
    "\2\17\3\0\41\17\1\63\13\17\16\0\2\17\3\0"+
    "\36\17\1\66\16\17\16\0\2\17\3\0\32\17\1\70"+
    "\22\17\16\0\2\17\3\0\40\17\1\73\10\17\1\74"+
    "\3\17\16\0\2\17\3\0\26\17\1\100\6\17\1\101"+
    "\1\102\16\17\16\0\2\17\3\0\37\17\1\105\1\106"+
    "\14\17\16\0\2\17\3\0\35\17\1\135\17\17\16\0"+
    "\2\17\3\0\41\17\1\30\13\17\16\0\2\17\3\0"+
    "\26\17\1\112\26\17\16\0\2\17\3\0\26\17\1\116"+
    "\3\17\1\117\6\17\1\120\13\17\16\0\2\17\3\0"+
    "\26\17\1\124\6\17\1\125\5\17\1\126\11\17\16\0"+
    "\2\17\3\0\32\17\1\131\6\17\1\132\13\17\16\0"+
    "\2\17\3\0\32\17\1\134\22\17\4\0\1\136\11\0"+
    "\2\136\3\0\55\136\11\137\1\140\66\137\1\56\1\141"+
    "\1\56\1\142\74\56\16\0\2\60\76\0\2\17\3\0"+
    "\14\17\1\143\40\17\16\0\2\17\3\0\41\17\1\144"+
    "\13\17\16\0\2\17\3\0\1\145\54\17\16\0\2\17"+
    "\3\0\11\17\1\146\43\17\16\0\2\17\3\0\26\17"+
    "\1\147\26\17\16\0\2\17\3\0\5\17\1\150\47\17"+
    "\16\0\2\17\3\0\33\17\1\151\21\17\16\0\2\17"+
    "\3\0\21\17\1\152\33\17\16\0\2\17\3\0\2\17"+
    "\1\153\12\17\1\154\37\17\16\0\2\17\3\0\46\17"+
    "\1\155\6\17\16\0\2\17\3\0\30\17\1\156\11\17"+
    "\1\154\12\17\16\0\2\17\3\0\11\17\1\157\43\17"+
    "\16\0\2\17\3\0\13\17\1\160\41\17\16\0\2\17"+
    "\3\0\14\17\1\161\40\17\16\0\2\17\3\0\36\17"+
    "\1\162\16\17\16\0\2\17\3\0\40\17\1\163\14\17"+
    "\16\0\2\17\3\0\41\17\1\164\13\17\16\0\2\17"+
    "\3\0\15\17\1\165\37\17\16\0\2\17\3\0\10\17"+
    "\1\166\10\17\1\167\33\17\16\0\2\17\3\0\42\17"+
    "\1\170\12\17\16\0\2\17\3\0\35\17\1\171\10\17"+
    "\1\172\6\17\16\0\2\17\3\0\4\17\1\173\50\17"+
    "\16\0\2\17\3\0\12\17\1\174\42\17\16\0\2\17"+
    "\3\0\17\17\1\175\35\17\16\0\2\17\3\0\44\17"+
    "\1\176\10\17\16\0\2\17\3\0\13\17\1\177\41\17"+
    "\16\0\2\17\3\0\1\200\20\17\1\201\33\17\16\0"+
    "\2\17\3\0\12\17\1\202\42\17\16\0\2\17\3\0"+
    "\40\17\1\203\14\17\16\0\2\17\3\0\26\17\1\204"+
    "\17\17\1\205\6\17\16\0\2\17\3\0\37\17\1\206"+
    "\15\17\16\0\2\17\3\0\11\17\1\207\43\17\16\0"+
    "\2\17\3\0\6\17\1\210\4\17\1\211\41\17\16\0"+
    "\2\17\3\0\17\17\1\212\35\17\16\0\2\17\3\0"+
    "\36\17\1\213\16\17\16\0\2\17\3\0\34\17\1\214"+
    "\3\17\1\215\14\17\16\0\2\17\3\0\44\17\1\216"+
    "\10\17\16\0\2\17\3\0\24\17\1\217\30\17\16\0"+
    "\2\17\3\0\13\17\1\220\41\17\16\0\2\17\3\0"+
    "\51\17\1\221\3\17\16\0\2\17\3\0\40\17\1\222"+
    "\14\17\16\0\2\17\3\0\17\17\1\223\35\17\16\0"+
    "\2\17\3\0\44\17\1\224\10\17\16\0\2\17\3\0"+
    "\32\17\1\225\22\17\4\0\1\226\11\0\2\226\3\0"+
    "\55\226\11\137\1\227\77\137\1\227\3\137\1\230\62\137"+
    "\1\0\1\141\114\0\2\17\3\0\11\17\1\231\43\17"+
    "\16\0\2\17\3\0\36\17\1\232\16\17\16\0\2\17"+
    "\3\0\20\17\1\233\34\17\16\0\2\17\3\0\14\17"+
    "\1\234\40\17\16\0\2\17\3\0\45\17\1\235\7\17"+
    "\16\0\2\17\3\0\10\17\1\236\44\17\16\0\2\17"+
    "\3\0\35\17\1\237\17\17\16\0\2\17\3\0\4\17"+
    "\1\240\12\17\1\241\35\17\16\0\2\17\3\0\4\17"+
    "\1\242\50\17\16\0\2\17\3\0\32\17\1\243\11\17"+
    "\1\244\10\17\16\0\2\17\3\0\32\17\1\245\22\17"+
    "\16\0\2\17\3\0\20\17\1\211\34\17\16\0\2\17"+
    "\3\0\1\246\54\17\16\0\2\17\3\0\21\17\1\247"+
    "\33\17\16\0\2\17\3\0\45\17\1\215\7\17\16\0"+
    "\2\17\3\0\46\17\1\250\6\17\16\0\2\17\3\0"+
    "\14\17\1\251\2\17\1\252\35\17\16\0\2\17\3\0"+
    "\2\17\1\253\52\17\16\0\2\17\3\0\4\17\1\254"+
    "\50\17\16\0\2\17\3\0\41\17\1\255\2\17\1\256"+
    "\10\17\16\0\2\17\3\0\30\17\1\257\24\17\16\0"+
    "\2\17\3\0\32\17\1\260\22\17\16\0\2\17\3\0"+
    "\13\17\1\261\41\17\16\0\2\17\3\0\4\17\1\262"+
    "\50\17\16\0\2\17\3\0\1\163\54\17\16\0\2\17"+
    "\3\0\26\17\1\163\26\17\16\0\2\17\3\0\6\17"+
    "\1\211\46\17\16\0\2\17\3\0\11\17\1\154\43\17"+
    "\16\0\2\17\3\0\14\17\1\263\40\17\16\0\2\17"+
    "\3\0\15\17\1\264\37\17\16\0\2\17\3\0\34\17"+
    "\1\215\20\17\16\0\2\17\3\0\36\17\1\154\16\17"+
    "\16\0\2\17\3\0\41\17\1\265\13\17\16\0\2\17"+
    "\3\0\42\17\1\266\12\17\16\0\2\17\3\0\10\17"+
    "\1\267\44\17\16\0\2\17\3\0\22\17\1\233\32\17"+
    "\16\0\2\17\3\0\14\17\1\163\40\17\16\0\2\17"+
    "\3\0\21\17\1\154\33\17\16\0\2\17\3\0\35\17"+
    "\1\270\17\17\16\0\2\17\3\0\47\17\1\235\5\17"+
    "\16\0\2\17\3\0\41\17\1\163\13\17\16\0\2\17"+
    "\3\0\46\17\1\154\6\17\16\0\2\17\3\0\21\17"+
    "\1\271\33\17\16\0\2\17\3\0\2\17\1\272\52\17"+
    "\16\0\2\17\3\0\46\17\1\273\6\17\16\0\2\17"+
    "\3\0\30\17\1\274\24\17\16\0\2\17\3\0\3\17"+
    "\1\275\51\17\16\0\2\17\3\0\31\17\1\276\23\17"+
    "\16\0\2\17\3\0\40\17\1\277\14\17\4\0\1\300"+
    "\11\0\2\300\3\0\55\300\11\137\1\227\3\137\1\141"+
    "\62\137\16\0\2\17\3\0\4\17\1\301\50\17\16\0"+
    "\2\17\3\0\32\17\1\302\22\17\16\0\2\17\3\0"+
    "\4\17\1\163\50\17\16\0\2\17\3\0\17\17\1\303"+
    "\35\17\16\0\2\17\3\0\32\17\1\163\22\17\16\0"+
    "\2\17\3\0\13\17\1\304\41\17\16\0\2\17\3\0"+
    "\40\17\1\305\14\17\16\0\2\17\3\0\17\17\1\271"+
    "\35\17\16\0\2\17\3\0\1\267\54\17\16\0\2\17"+
    "\3\0\15\17\1\306\37\17\16\0\2\17\3\0\44\17"+
    "\1\273\10\17\16\0\2\17\3\0\26\17\1\270\26\17"+
    "\16\0\2\17\3\0\42\17\1\307\12\17\16\0\2\17"+
    "\3\0\11\17\1\163\43\17\16\0\2\17\3\0\1\310"+
    "\54\17\16\0\2\17\3\0\26\17\1\311\26\17\16\0"+
    "\2\17\3\0\17\17\1\312\35\17\16\0\2\17\3\0"+
    "\10\17\1\313\44\17\16\0\2\17\3\0\10\17\1\211"+
    "\44\17\16\0\2\17\3\0\13\17\1\314\41\17\16\0"+
    "\2\17\3\0\44\17\1\315\10\17\16\0\2\17\3\0"+
    "\35\17\1\316\17\17\16\0\2\17\3\0\35\17\1\215"+
    "\17\17\16\0\2\17\3\0\40\17\1\317\14\17\16\0"+
    "\2\17\3\0\21\17\1\320\33\17\16\0\2\17\3\0"+
    "\17\17\1\321\35\17\16\0\2\17\3\0\17\17\1\322"+
    "\35\17\16\0\2\17\3\0\4\17\1\323\50\17\16\0"+
    "\2\17\3\0\44\17\1\324\10\17\16\0\2\17\3\0"+
    "\32\17\1\325\22\17\16\0\2\17\3\0\3\17\1\175"+
    "\51\17\16\0\2\17\3\0\31\17\1\176\23\17\16\0"+
    "\2\17\3\0\14\17\1\154\40\17\16\0\2\17\3\0"+
    "\20\17\1\163\34\17\16\0\2\17\3\0\41\17\1\154"+
    "\13\17\16\0\2\17\3\0\45\17\1\163\7\17\16\0"+
    "\2\17\3\0\1\326\54\17\16\0\2\17\3\0\26\17"+
    "\1\327\26\17\16\0\2\17\3\0\46\17\1\330\6\17"+
    "\4\0\1\331\11\0\2\331\3\0\55\331\16\0\2\17"+
    "\3\0\1\332\54\17\16\0\2\17\3\0\26\17\1\333"+
    "\26\17\16\0\2\17\3\0\10\17\1\323\44\17\16\0"+
    "\2\17\3\0\35\17\1\325\17\17\16\0\2\17\3\0"+
    "\21\17\1\211\33\17\16\0\2\17\3\0\46\17\1\215"+
    "\6\17\16\0\2\17\3\0\13\17\1\334\41\17\16\0"+
    "\2\17\3\0\40\17\1\335\14\17\16\0\2\17\3\0"+
    "\21\17\1\336\33\17\16\0\2\17\3\0\12\17\1\233"+
    "\42\17\16\0\2\17\3\0\21\17\1\175\33\17\16\0"+
    "\2\17\3\0\46\17\1\337\6\17\16\0\2\17\3\0"+
    "\37\17\1\235\15\17\16\0\2\17\3\0\46\17\1\176"+
    "\6\17\16\0\2\17\3\0\17\17\1\340\35\17\16\0"+
    "\2\17\3\0\14\17\1\303\40\17\16\0\2\17\3\0"+
    "\13\17\1\175\41\17\16\0\2\17\3\0\17\17\1\163"+
    "\35\17\16\0\2\17\3\0\40\17\1\176\14\17\16\0"+
    "\2\17\3\0\44\17\1\163\10\17\16\0\2\17\3\0"+
    "\3\17\1\341\51\17\16\0\2\17\3\0\31\17\1\342"+
    "\23\17\16\0\2\17\3\0\44\17\1\343\10\17\4\0"+
    "\1\344\11\0\2\344\3\0\55\344\16\0\2\17\3\0"+
    "\13\17\1\211\41\17\16\0\2\17\3\0\40\17\1\215"+
    "\14\17\16\0\2\17\3\0\21\17\1\345\33\17\16\0"+
    "\2\17\3\0\46\17\1\346\6\17\16\0\2\17\3\0"+
    "\1\323\54\17\16\0\2\17\3\0\26\17\1\325\26\17"+
    "\16\0\2\17\3\0\1\272\54\17\16\0\2\17\3\0"+
    "\4\17\1\347\50\17\16\0\2\17\3\0\32\17\1\350"+
    "\22\17\16\0\2\17\3\0\26\17\1\274\26\17\16\0"+
    "\2\17\3\0\4\17\1\154\50\17\16\0\2\17\3\0"+
    "\32\17\1\154\22\17\16\0\2\17\3\0\17\17\1\211"+
    "\35\17\16\0\2\17\3\0\44\17\1\215\10\17";

  private static int [] zzUnpacktrans() {
    int [] result = new int[14080];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\43\1\3\0\1\1\1\11"+
    "\1\1\1\11\54\1\3\0\1\11\64\1\2\0\50\1"+
    "\1\0\30\1\1\0\12\1\1\11\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[232];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private TextColor textColor(long start, int size, Color color) {
        return new TextColor((int)start, size, color);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerColor(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public TextColor yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* Ignorar */
            }
          // fall through
          case 11: break;
          case 2:
            { return textColor(yychar, yylength(), new Color(0,0,0));
            }
          // fall through
          case 12: break;
          case 3:
            { return textColor(yychar, yylength(), new Color(35,120,147));
            }
          // fall through
          case 13: break;
          case 4:
            { return textColor(yychar, yylength(), new Color(146,146,146));
            }
          // fall through
          case 14: break;
          case 5:
            { return textColor(yychar, yylength(), Color.RED);
            }
          // fall through
          case 15: break;
          case 6:
            { return textColor(yychar, yylength(), Color.GREEN);
            }
          // fall through
          case 16: break;
          case 7:
            { return textColor(yychar, yylength(), new Color(155,38,182));
            }
          // fall through
          case 17: break;
          case 8:
            { return textColor(yychar, yylength(), new Color(105,99,32));
            }
          // fall through
          case 18: break;
          case 9:
            { return textColor(yychar, yylength(), new Color(148,58,173));
            }
          // fall through
          case 19: break;
          case 10:
            { return textColor(yychar, yylength(), new Color(224,195,12));
            }
          // fall through
          case 20: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
